---
- name: OpenSLX dracut | Build initramfs
  shell: "{{ builder_path }} -s -d -p {{ builder_target }} {{ builder_extra_args }}"
  args:
    creates: "{{ builder_target }}"

# TODO: use dracut option to prevent it from copying the system's loop kernel module:
#       --omit-driver loop
# define variable for extra dracut args for example.
- name: Remove default loop module
  shell: "cd {{ builder_path | dirname }}; mkdir tmp; cd tmp; /usr/lib/dracut/skipcpio ../initramfs | zcat | cpio -ivd; rm -f lib/modules/*/kernel/drivers/block/loop.ko.xz; find . | cpio -o -H newc > ../initramfs; cd ..; rm -rf tmp"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: OpenSLX dracut | Retrieve initramfs and kernel (+ hack for weird /@ prefix of BOOT_IMAGE)
  fetch:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/boot_files/"
    fail_on_missing: yes
    flat: yes
  with_items:
    - "{{ builder_target }}"
    - "{{ ansible_cmdline.BOOT_IMAGE | regex_replace('^.*(/boot/.*)+$', '\\1') }}"

- name: OpenSLX dracut | Cleanup
  file:
    path: "{{ builder_path | dirname }}"
    state: absent
