---
- name: OpenSLX dracut | Build initramfs
  shell: >-
    {{ builder_path }}
    --debug
    --update
    --file-path
    {{ builder_target }}
    {{ builder_kernel_args }}
    {{ builder_distro_args | default() }}
    {{ builder_extra_args | default() }}
  args:
    creates: "{{ builder_target }}"

- name: OpenSLX dracut | Retrieve initramfs and kernel
  fetch:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/boot_files/"
    fail_on_missing: yes
    flat: yes
  with_items:
    - "{{ builder_target }}"
    - "{{ builder_kernel_path }}"

- name: OpenSLX dracut | Cleanup
  file:
    path: "{{ builder_path | dirname }}"
    state: absent
