---
- set_fact:
    pkgnames:
      - epel-release
      - kernel-devel
      - fuse-devel
      - jansson-devel
      - glib2-devel
      - pixman-devel
      - libewf-devel
      - afflib-devel
      - device-mapper
      - wget
      - systemd-networkd
      - systemd-resolved
      - kexec-tools
      - kmod-devel
  when:
      - ansible_distribution == "CentOS"
- set_fact:
    pkgnames:
      - curl
      - libfuse-dev
      - libglib2.0-dev
      - libpixman-1-dev
      - libewf-dev
      - libafflib-dev
      - libjansson-dev
      - dmsetup
      - iputils-arping
      - kexec-tools
      - libkmod-dev
      - python
  when:
      - ansible_distribution == "Ubuntu"
