---
- name: OpenSLX dracut | Create download destination directory
  file:
    path: "{{ builder_path | dirname }}"
    state: directory

- name: OpenSLX dracut | Download bootstrap script
  get_url:
    url: "{{ builder_url }}"
    checksum: "{{ builder_checksum }}"
    dest: "{{ builder_path }}"
    mode: 0550

- name: OpenSLX dracut | Initialize repository
  shell: "{{ builder_path }} --init"
  args:
    creates: "${{ builder_path | dirname }}/dracut/dracut.sh"

- name: OpenSLX dracut | Get distro specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
      - "files/distro_specific/{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
      - "files/distro_specific/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "files/distro_specific/{{ ansible_distribution }}.yml"

