---
- name: OpenSLX dracut | Create download destination directory
  file:
    path: "{{ builder_path | dirname }}"
    state: directory

- name: OpenSLX dracut | Get bootstrap script (build-initramfs.sh)
  get_url:
    url: "{{ builder_url }}"
    dest: "{{ builder_path }}"
    mode: 0650
    force: yes

- name: OpenSLX dracut | Include distro specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/distro/{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    - "{{ role_path }}/tasks/distro/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ role_path }}/tasks/distro/{{ ansible_distribution }}.yml"

- name: OpenSLX dracut | Include distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/vars/distro/{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    - "{{ role_path }}/vars/distro/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ role_path }}/vars/distro/{{ ansible_distribution }}.yml"

- name: OpenSLX dracut | Initialize repository
  shell: >-
    {{ builder_path }}
    --debug
    --update
    --init
    {{ builder_kernel_args }}
    {{ builder_distro_args | default() }}
    {{ builder_extra_args | default() }}
  args:
    creates: "${{ builder_path | dirname }}/dracut/dracut.sh"
