---
- name: OpenSLX dracut | Create download destination directory
  file:
    path: "{{ builder_path | dirname }}"
    state: directory

- name: OpenSLX dracut | Get bootstrap script (build-initramfs.sh)
  get_url:
    url: "{{ builder_url }}"
    dest: "{{ builder_path }}"
    mode: 0550

- name: OpenSLX dracut | Get distro specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "tasks/distro/{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    - "tasks/distro/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "tasks/distro/{{ ansible_distribution }}.yml"

- name: OpenSLX dracut | Include distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/distro/{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    - "vars/distro/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "vars/distro/{{ ansible_distribution }}.yml"

- name: OpenSLX dracut | Initialize repository
  shell: "{{ builder_path }} --init --debug {{ builder_extra_args }}"
  args:
    creates: "${{ builder_path | dirname }}/dracut/dracut.sh"
