---
- name: DevTools | Get distro specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
      - "tasks/distro/{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
      - "tasks/distro/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "tasks/distro/{{ ansible_distribution }}.yml"
