---
- name: CentOS-7 | Install packages
  yum:
     name: "{{ packages }}"
     state: latest
     update_cache: yes
  vars:
    packages:
      - "epel-release"
      - "@development tools"
      - "cmake"
      - "git"
