---
- name: Hack fix dnbd3 blk.c for Ubuntu newer kernels
  replace:
    dest: "{{ gittarget }}/builder/modules.d/dnbd3-rootfs/scripts/build.sh"
    regexp: 'make -j4 dnbd3 dnbd3-client'
    replace: 'sed -i "s/backing_dev_info.ra_pages/backing_dev_info->ra_pages/g" blk.c && make -j4 dnbd3 dnbd3-client'
    backup: yes
  when:
    - ansible_distribution == "Ubuntu"
- name: Hack fix dnbd3 blk.h for CentOS kernels with backports
  replace:
    dest: "{{ gittarget }}/builder/modules.d/dnbd3-rootfs/scripts/build.sh"
    regexp: 'make -j4 dnbd3 dnbd3-client'
    replace: 'sed -i "s/KERNEL_VERSION.*/KERNEL_VERSION\(3, 10, 0\)/g" blk.h && make -j4 dnbd3 dnbd3-client'
    backup: yes
  when:
    - ansible_distribution == "CentOS"
