---
- name: CentOS-7 | Install packages
  yum:
     name: "{{ packages }}"
     state: latest
     update_cache: yes
  vars:
     packages:
       - kernel-devel
       - fuse-devel
       - jansson-devel
       - glib2-devel
       - pixman-devel
       - libewf-devel
       - afflib-devel
       - device-mapper
       - wget
       - systemd-networkd
       - systemd-resolved
       - kexec-tools
       - kmod-devel
       - haveged
