---
- name: CentOS-7 | Install default packages
  yum:
    name:
      - kernel-devel
      - glib2-devel
      - pixman-devel
      - libewf-devel
      - afflib-devel
      - fuse-devel
      - device-mapper
      - wget
      - kexec-tools
      - kmod-devel
      - haveged
      - cmake
      - cmake3
      - centos-release-scl
      - redhat-lsb
    state: latest
    update_cache: yes
  tags:
    - always

# need a second task since 'centos-release-scl' configures a new repo
- name: CentOS-7 | Install developer toolset version 7 from SCL
  yum:
    name:
      - devtoolset-7
      - devtoolset-7-libatomic-devel
      - llvm-toolset-7-git-clang-format
    state: latest
    update_cache: yes
  tags:
    - always
