---
- name: Alma|Rocky|Centos 9 | Enable devel repo
  command: dnf config-manager --enable devel

- name: Alma|Rocky|Centos 9 | Install packages
  dnf:
     name: "{{ packages }}"
     state: latest
     update_cache: yes
  vars:
     packages:
       - afflib-devel
       - clang-tools-extra
       - device-mapper
       - elfutils-libelf-devel
       - fuse3-devel
       - glib2-devel
       - haveged
       - jansson-devel
       - kernel-devel
       - kexec-tools
       - kmod-devel
       - libewf-devel
       - pixman-devel
       - wget
