---
- name: Ubuntu-18 | Install packages
  apt:
     name: "{{ packages }}"
     state: latest
     update_cache: yes
  vars:
     packages:
       - libfuse-dev
       - libglib2.0-dev
       - libpixman-1-dev
       - libewf-dev
       - libafflib-dev
       - libjansson-dev
       - dmsetup
       - iputils-arping
       - kexec-tools
       - libkmod-dev

- name: Hack fix dnbd3 blk.c for Ubuntu newer kernels
  replace:
    dest: "{{ builder_path | dirname }}/systemd-init.git/builder/modules.d/dnbd3-rootfs/helper/build.inc"
    regexp: 'make -j4 dnbd3 dnbd3-client'
    replace: 'sed -i "s/backing_dev_info.ra_pages/backing_dev_info->ra_pages/g" blk.c && make -j4 dnbd3 dnbd3-client'
    backup: yes
  when:
    - ansible_distribution == "Ubuntu"
